### ISSUE TITLE
Not compatible with symfony3

### ISSUE THREAD

**Issue by kazenojiyu** [vihuvac/recaptcha-bundle#1]
Hello,

I've seen that this bundle is not compatible with symfony3.
I have these warnings :
- Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.
- Vihuvac\Bundle\RecaptchaBundle\Form\Type\RecaptchaType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0.
- Vihuvac\Bundle\RecaptchaBundle\Form\Type\RecaptchaType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0.

It's possible to fix these warnings ?

**Comment by vihuvac** [comment]
Issue fixed with the new release **v2.1.0**.
