### ISSUE TITLE
How does this bundle differ from EWZRecaptchaBundle? 

### ISSUE THREAD

**Issue by konradmietelski** [vihuvac/recaptcha-bundle#16]
Hello,

I'm curious how does this bundle differ from EWZRecaptchaBundle? For what I can see it's copy-pasted code without forking for most of the time. If there is any additional feature?

Regards.

**Comment by vihuvac** [comment]
@broiniac closing it 'cause it's not an issue, this topic may be discussed on [gitter](https://gitter.im/vihuvac/recaptcha-bundle).
