### ISSUE TITLE
Problem with "Validation groups" in SF3

### ISSUE THREAD

**Issue by jeanassy** [vihuvac/recaptcha-bundle#17]
Hello,

I'm facing this problem, I'm using validation groups on the registration form, and if i use the following code, i can submit the form without even ticking the recaptcha checkbox !

```
$builder->add('recaptcha',RecaptchaType::class, array(

        'attr'        => array(
            'options' => array(
                'theme' => 'light',
                'type'  => 'image',
                'size'  => 'normal'
            )
        ),
        'mapped'      => false,
        'constraints' => array(
            new RecaptchaTrue()
        )
    ));
```
I also face the same problem even if add this in the entity class (and remove the "mapped" and "constraints" from the form field):

```
  /**
     * @Recaptcha\IsTrue(groups={"Signup"})
     */
    public $recaptcha;

```

Any idea how to solve this?

**Comment by vihuvac** [comment]
@jeanassy hi! It sounds like a kind of missing settings! Are configuring correctly the field in the form within the twig template? I'd recommend you to use a form class, that's a better practice for Symfony Forms, then you can set your options within the ___default resolvers___ and even enable the ```error_bubbling``` method.

**Comment by jeanassy** [comment]
@vihuvac The error_bubbling is enabled already but im using the form class. 
But i found the solution for it, and i think you should mention it in the documentation to make life easier for developers. The solution is by adding the validation_groups in the recaptcha form field, like below:

```
 ->add('recaptcha', RecaptchaType::class, array(
                    'attr' => array(
                         //
                    ),
                   
                    "validation_groups"=>"Signup", 
                    'error_bubbling' => true,
                ))

```

**Comment by vihuvac** [comment]
@jeanassy good to know you could solve the problem you had. Those settings should not be passed straight to the form field, those should be assigned via ```configureOptions``` like the official *Symfony* doc indicates, that's why this kind of settings are not mentioned in the bundle due to everything apart and regarding to *Symfony* forms has its own official doc, e.g.

```php
...
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        "data_class"         => YourFormType::class,
        "error_bubbling"     => true,
        "validation_groups"  => <your-validation-groups>,
        "translation_domain" => <your-translation-domain>  // If you need to translate labels and placeholders.
    ]);
}
...
```

**Comment by jeanassy** [comment]
Actually that's what i was trying to tell you! I was passing the validation groups in the $resolver, but it didn't work until i added "validation_groups" in the recaptcha form field !
